# discord stuff
BOT_APPLICATION_ID = "discord bot id (technically in token but ehh)"
BOT_TOKEN = "discord bot token"
# BOT_LOGGING_CHANNEL_ID = "1355064546041004124"

# integration
ASSET_MANAGER_FOLDER = "/home/ah/Desktop/salt-asset-manager/asset-manager"

# SOMNIA_SHANNON_RPC_ENDPOINT = "https://rpc.ankr.com/somnia_testnet"
# SOMNIA_SHANNON_RPC_ENDPOINT = "https://50312.rpc.thirdweb.com/THIRDWEB_API_KEY"
SOMNIA_SHANNON_RPC_ENDPOINT = "https://dream-rpc.somnia.network/"
SEPOLIA_ARBITRUM_RPC_ENDPOINT = "https://sepolia-rollup.arbitrum.io/rpc"
SEPOLIA_ETHERIUM_RPC_ENDPOINT = "https://sepolia.drpc.org"
FAUCET_TESTNET_SALT_ACCOUNT_ADDRESS = "0xcedc0DD99D036d73dd39509Ef7970A998D3e7FD8"

# private key for my test account, which is in the test salt org
PRIVATE_KEY = "private key for you personal acc setup with salt"
ORCHESTRATION_NETWORK_RPC_NODE_URL = "https://sepolia-rollup.arbitrum.io/rpc"
